backend:
  name: git-gateway
  branch: master

media_folder: "static/uploads"
public_folder: "/uploads"
site_url: https://thestudy-books.com
logo_url: https://thestudy-books.com/images/logo.png

collections:
  - name: "products"
    label: "Books"
    label_singular: "Book"
    folder: "content/products"
    create: true
    filter: {field: "type", value: "products"}
    view_filters:
      - label: "Old Testament"
        field: categories
        pattern: "Old Testament"
      - label: "New Testament"
        field: categories
        pattern: "New Testament"
      - label: "Confessional/Topical"
        field: categories
        pattern: "Confessional Topical"
    sortable_fields: ["title","productID","author","formats","price","publisher"]
    fields:
      - label: "ProductID"
        name: "productID"
        widget: "number"
        value_type: "int"
        hint: "Enter a unique 3 or 4 digit Product number."
        pattern: ['\d{3,4}', "3 or 4 digit number"]
      - label: "File Name"
        name: "slug"
        widget: "number"
        value_type: "int"
        hint: "Make this the same as the ProductID."
      - {label: "Book Title", name: "title", widget: "string", hint: "Add ' - ePub' to the end of the Title for Digital versions of books."}
      - label: "Book SubTitle"
        name: "subtitle"
        widget: "text"
        required: false
        hint: "This is optional, but do split up the Title into Title and Subtitle if appropriate."
      - label: "IngramSpark Book"
        name: "IngramSpark"
        widget: "boolean"
        default: false
        required: false
        hint: "Turn this on if the book should be purchased through the IngramSpark Aer.io store."
      - label: "Preview PDF"
        name: "preview"
        widget: "file"
        media_folder: "/static/uploads/previews"
        hint: "Upload and use a preview PDF for this book."
        required: false
      - label: "Description"
        name: "description"
        widget: "markdown"
        hint: "Enter a description of the Book"
      - label: "Price $"
        name: "price"
        widget: "number"
        value_type: "float"
      - label: "Sale Price $"
        name: "salePrice"
        widget: "number"
        value_type: "float"
        required: false
        hint: "Only enter a sale price if it differs from the regular price."
      - label: "SnipCart UUID"
        name: "snipcartUUID"
        widget: "string"
        required: false
        hint: "This is the UUID from Snipcart for Digital resources that have been uploaded to Snipcart."
      - label: "Categories"
        name: "categories"
        widget: "select"
        multiple: true
        options: ["Old Testament","New Testament","Confessional Topical","Digital (ePub)","Featured","Paper","The Study Books"]
        default: ["The Study Books"]
        min: 1
      - label: "Cover Image"
        name: "cover"
        widget: "image"
        media_folder: "/static/uploads/covers"
        allow_multiple: false
        hint: "Uploaded cover image. Please scale image too 400x600 before uploading."
      - label: "Author(s)"
        name: "author"
        widget: "string"
      - label: "Publisher"
        name: "publisher"
        widget: "string"
        default: "The Study"
      - label: "ISBN"
        name: "ISBN"
        widget: "string"
        required: false
        hint: "Enter an ISBN number if there is one available."
      - label: "Published Year"
        name: "publishYear"
        widget: "string"
        pattern: ['\d{4}', "Year of publishing"]
      - label: "Page Count"
        name: "pageCount"
        widget: "number"
        value_type: "int"
      - label: "Formats"
        name: "formats"
        widget: "select"
        options: ["Digital (ePub)","Paper"]
        default: ["Paper"]
        multiple: false
      - label: "ID of Parent (Paper book) Product"
        name: "parentID"
        widget: "relation"
        collection: "products"
        value_field: "productID"
        search_fields: ["author","title","productID"]
        display_fields: ["productID","title","author"]
        required: false
        hint: "Only use for ePub products to indicate Product ID of main book."
      - label: "ID of Child (ePub) Product"
        name: "childID"
        widget: "relation"
        collection: "products"
        value_field: "productID"
        search_fields: ["author","title","productID"]
        display_fields: ["productID","title","author"]
        required: false
        hint: "Only use for Paper books with an associated ePub to indicate the Product ID of the corresponding ePub."
      - {label: "Type", name: "type", widget: "Hidden", default: "products"}
      - label: "Author Information"
        name: "body"
        widget: "markdown"
        hint: "Use a second level heading (##) with 'About the Author' to start."
        required: false

  - label: "Site Pages"
    name: "pages"
    files:
      - label: "FAQ Page"
        name: "faq"
        file: "data/faq.yml"
        fields:
          - name: faqItem
            label: "FAQ Items"
            label_singular: "FAQ Item"
            widget: "list"
            fields:
              - {label: "Question", name: "title", widget: "string"}
              - {label: "Answer", name: "content", widget: "string"}